id: P006950
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5859
  title: ཆོས་ཀྱི་སྡོམ་བཞི་བསྟན་པའི་མདོ་
  author: ''
  volumes:
    dee9aba6f53648ab80c67d674e6b635f:
      image_group_id: I1KG5885
      title: ''
      volume_number: 1
      total_pages: 318
ebook_metadata:
  title: ཆོས་ཀྱི་སྡོམ་བཞི་བསྟན་པའི་མདོ་
  author: ''
  sku: P006950
  cover: cover.jpg
  layers:
  - pagination
